### ISSUE TITLE
Use correspondent HTTP verbs for collections

### ISSUE THREAD

**Issue by matteodem** [stubailo/meteor-rest#10]
Cool package, looking forward to using it. It is common best practice to understand endpoints as resources, where you use HTTP verbs to specify the corresponding action. It'd be cool to have this the same way here.

see http://www.restapitutorial.com/lessons/httpmethods.html

**Comment by stubailo** [comment]
Yep, I totally agree - the best way to do that right now is with Restivus: https://atmospherejs.com/nimble/restivus

I assume what you're referring to is the `/methods/collection/insert`, `/methods/collection/update`, `/methods/collection/remove` methods?

So I guess it would end up like the below?

```http
POST /collection
PATCH /collection/:_id
DELETE /collection/:_id
```

**Comment by matteodem** [comment]
Exactly, also: 

```http
GET /collection
GET collection/:_id
```

**Comment by raix** [comment]
@stubailo the get `id` is a good example of a publish that could be defined in `allow`/`deny` rules.

**Comment by stubailo** [comment]
@matteodem @raix It would be nice to have the default `GET` routes, but for the first go I'm going to just do CUD (rather than CRUD) - if you want to define GET routes you can always use Restivus, or define a publication with a custom URL.

**Comment by stubailo** [comment]
First pass at this done: https://github.com/stubailo/meteor-rest/blob/master/packages/rest/README.md#collection-methods

**Comment by stubailo** [comment]
Opened a new issue for GET https://github.com/stubailo/meteor-rest/issues/15
