### ISSUE TITLE
How to filter documents by this.userId

### ISSUE THREAD

**Issue by achirkof** [stubailo/meteor-rest#101]
Hello!
Usual behavior of Meteor publication/subscription give the ability to filter documents by authenticated user.
For example:

```
Meteor.publish('books', function() {
    return Books.find({
        createdBy: this.userId
    });
});
```

Return me only books created by current user.

But using this package how I can repeat this behavior? Now the same publication as above returns me 
empty {}.
I think it is because I don't sending authentication information 
`curl http://mysite.com:3000/publications/books`.
How I should do it correctly?

**Comment by romans127** [comment]
Console log this and see what's available.  Then try passing an argument to
the function then log that.   Chances are this is just a matter of
scoping.  I've seen that error where the value Wed expect to be a string
ended up being scoped differently like this.data.userid or something to
that affect.

**Comment by achirkof** [comment]
@rwatts3 `console.log(this.userId)` returns `null`. And as I think it is because I don't authorized. I don't know how to do it. How to send authorization info to publication.

**Comment by romans127** [comment]
Hmm it should be passed on the call back if I'm not mistaken.

**Comment by achirkof** [comment]
Ok. Got it.
First you have to authorize:
`curl http://yoursite.com/users/login -X POST -d "email=user@mail.com&password=userpassword"`
and you receive a reply:

```
{
  "id": "BeNTtaupkj5JfpJcH",
  "token": "H2WWh3PwOcYa7tJBm71V-us_ym84JCD89vru2MRmhJB",
  "tokenExpires": "2016-07-24T07:26:47.119Z"
}
```

Then use token to get documents you have authorize:
`curl http://yoursite.com:3000/publications/books -H "Authorization: Bearer H2WWh3PwOcYa7tJBm71V-us_ym84JCD89vru2MRmhJB"`

**Comment by stubailo** [comment]
If there is anything that could be clearer in the docs, please file a PR!
