### ISSUE TITLE
Add option for token refresh

### ISSUE THREAD

**Issue by raix** [stubailo/meteor-rest#12]
When authenticating it should return:
```js
{
  access_token: '',
  expires_in: 10, // Sec
  refresh_token: '' // Use this to refresh token login
}
```

**Comment by stubailo** [comment]
Right now, the login API returns a long-lasting token that can be revoked by the user if necessary, and the token is checked every time a method is called. In this case, is there still a need for a refresh token? I thought the main point of a refresh token was in the case where you don't check the access token against a database for expiration.

**Comment by raix** [comment]
I have to give it some thought, i see your point

**Comment by stubailo** [comment]
Will close for now.
