### ISSUE TITLE
Are Promised-based methods supported?

### ISSUE THREAD

**Issue by timeyr** [stubailo/meteor-rest#123]
I am trying to add a route to a method that returns a Promise, like so:

```
Meteor.method('myMethod',
    async function myMethod(arg) {
        return await someAsyncFunction(arg);
    }
);
```
But it looks like the result of an HTTP call always yields `status 200` and `data: {}`, no matter what value the Promise resolves to (or an error is thrown).

EDIT: It works if we use `meteor:promise` (https://github.com/meteor/promise), i.e.

```
Meteor.method('myMethod',
    function myMethod(arg) {
        return Promise.await(someAsyncFunction(arg));
    }
);
```
Too bad I will probably never understand how that package works... I read Ben's presentation about Fibers and Promises a couple of times, but I just can't wrap my mind around it...

**Comment by stubailo** [comment]
Interesting, I think this is probably a bug, and can be fixed by adding a `Promise.resolve` around the method result here: https://github.com/stubailo/meteor-rest/blob/359532f8ac38e246731c02ee70436ee26d70743b/packages/rest/rest.js#L218
