### ISSUE TITLE
DDP methods should just match 1:1 on HTTP?

### ISSUE THREAD

**Issue by raix** [stubailo/meteor-rest#13]
```js
Meteor.publish("widgets-above-index", function (index) {
  return Widgets.find({index: {$gt: parseInt(index, 10)}});
}, {
  url: "widgets-with-index-above/:0"
});
```

Should be:
```js
Meteor.publish("widgets-above-index", function (index /*, args */) {
  return Widgets.find({index: {$gt: parseInt(index, 10)}});
});
```
*args is named arguments, its put last after positioned arguments*

**Comment by stubailo** [comment]
How would you call this publication over HTTP?

**Comment by stubailo** [comment]
Re-reading your comment, I think what you mean is you can only pass named arguments over HTTP, I feel like that wouldn't be so good - you would have to rewrite all of your publications to take only named arguments.

**Comment by raix** [comment]
Nope, positionen args are put first, then as last positionen arg would be the named args object. So it would not require rewriting.

**Comment by stubailo** [comment]
Can you give me a sample HTTP request that would call that publication?

**Comment by raix** [comment]
```js
  HTTP.get('api/users/arg0/arg1/arg2?_id:12&filter[created_at_gt]=2015-01-01');

  Meteor.publish('users', function(arg0, arg1, arg2, args) {
    // arg0 == 'arg0' etc.
    // args._id == 12
    // args.filter == { created_at_gt: '2015-01-01' }
    // query = filterToMongoSeletor(args.filter || {});
  });
```

You can add named arguments either via body or querystring. Positioned arguments are set as part of the url.

*I can hear @jperl if I can share the filter package etc. with you, maybe open source later on?*

**Comment by raix** [comment]
```js
  HTTP.get('api/users?only=named_args');

  Meteor.publish('users', function(args) {});
```

```js
  HTTP.get('api/users/only/positioned/arguments');

  Meteor.publish('users', function(only, positioned, arguments, args) {
    // args is always added last, if not set then null or {}?
  });
```

**Comment by jperl** [comment]
@raix it would be great if you could work on this

**Comment by stubailo** [comment]
I think #16 might actually address this concern - I should confirm later and add some tests about it.
