### ISSUE TITLE
How to use Authorization: Bearer <token> ?

### ISSUE THREAD

**Issue by bhanuprasad04** [stubailo/meteor-rest#149]
below are my implementation for rest service by using simple rest:
if(Meteor.isServer) {
JsonRoutes.Middleware.use('/auth', JsonRoutes.Middleware.parseBearerToken);
JsonRoutes.Middleware.use('/auth', JsonRoutes.Middleware.authenticateMeteorUserByToken);
JsonRoutes.ErrorMiddleware.use(RestMiddleware.handleErrorAsJson);
JsonRoutes.setResponseHeaders({
  "Cache-Control": "no-store",
  "Pragma": "no-cache",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, PUT, POST, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Requested-With"
});
Meteor.publish('test', function () {
    return Meteor.users.find({});
  }, {
    url: 'auth/testurl',
    httpMethod: 'post',
  });
 
}
So based on my above implementation my rest-endpoint would be like this 
**http://localhost:3000/auth/testurl**

The above endpoint working perfectly fine and I'M getting the result also.
But I want to use **Authorization: Bearer <token>** for the above endpoint.
I know how to get the token and how to pass it, but i am not understanding how to validate the token and restrict the endpoint(If token is invalid).
Could you please help me how to do this .

**Comment by TechplexEngineer** [comment]
Try using `X-Auth-Token` and `X-User-Id` headers
