### ISSUE TITLE
Generic way to get documents from database without Meteor.publish

### ISSUE THREAD

**Issue by stubailo** [stubailo/meteor-rest#15]

**Comment by raix** [comment]
We could add a 'view' to allow rules, having a function that returns a restriction query eg. Based on user role. What ever query the user want to make it will also have the restrictive query.

Eg.
~~~js
  foo.allow({
    Return { deleted: { $ne: true } };
  });
~~~

**Comment by raix** [comment]
In view... (On iPhone atm)

**Comment by raix** [comment]
On the server it would be nice to have insert/Update/remove/find/findone for a user. Eg.
~~~
Foo.insertFor(this.userId, ...
~~~

**Comment by stubailo** [comment]
What about something like:

```js
Accounts.runAsUser(userId, function () {
  Foo.insert({x: y});
});
```

**Comment by raix** [comment]
That could work, setting a user env on the server. It could also do the job for find restricted by allow/deny query rules for view/find

**Comment by raix** [comment]
```js
  Meteor.users.allow({
    find: function(userId) {
      // Allow users to see their own details
      return { _id: userId };
    }
  });

  Meteor.users.deny({
    find: function(userId) {
      // Deleted users may not be shown
      return { deletedAt: true };
    }
  });
```

```js
  // Generic publish
  Meteor.publish('users', function(args) {
    return Accounts.runAsUser(this.userId, function() {
      if (args === ''+args) {
        // This is a positioned arg "id"
        return Meteor.users.find({ _id: args });
      } else {
        // We will convert the args into a mongo query, set max limit of elements
        // this will also support filtering and pagination
        var query = new argumentsToMongoQuery(args, { maxLimit: 100 });
        // Return the user restricted cursor
        return Meteor.users.find(query.selector, query.options);
      }
    });
  });
```

**Comment by aldeed** [comment]
I don't like stuffing `find` into allow/deny. I don't like allow/deny API in the first place (why I created https://github.com/ongoworks/meteor-security), but for read security in particular, it seems poorly suited.

1. Field security should be included along with default selector.
2. Separating into allow vs. deny feels especially forced since we're just providing defaults.

I'd prefer a separate way of defining the restricted find. Then beyond that, I like the idea of `Accounts.runAsUser`, which would pass writes through allow/deny and pass reads through restricted find.

Here's an idea, a variation of what @raix came up with outside of this ticket:

```js
Meteor.users.baseFind(function (userId) {
  return this.find({_id: userId}, {fields: {username: 1}});
});
```

Then when within `Accounts.runAsUser`, deconstruct the cursor and merge it with any `find` calls that take place. (Reconciling included and omitted fields could get tricky.)

My thought was to use a `find` call because it's familiar and logical, but something like this could work as well:

```js
Meteor.users.baseSelector(function (userId) {
  return {_id: userId};
});

Meteor.users.allowedFields(function (userId) {
  return ['username'];
});
```

Broadly, this would seem to be a step toward defining all CRUD security in one file with one simple API, which I really like as a pattern.

**Comment by raix** [comment]
I sort of like the allow/deny rules - I thought about having a `field` restrictor, but as you say filtering the cursor afterwards could be tricky unless the rules are clever enough to spin up two subscriptions one containing the public fields and one containing the private fields.

In practice it would be nice to declare security pr. user role keeping things clear and flexible.
If we look at filesystem security we have a similar pattern to allow/deny - it's on document level.

I've been tossing around ideas in https://raix.hackpad.com/Schemas-FTUKBxszobi - The idea is to have sort of a schema where we declare security pr. field pr. role - this could compile down to allow/deny rules etc. We could automate a lot of things from the schema, eg. it could compile into anything really.
It's very declarative, making it easier to reason about - but I guess less flexible.

I kinda like the `Account.runAsUser(userId, function() {});` on the server to simulate db access available to one user - this should apply on all access.

*CRUDL*

**Comment by aldeed** [comment]
Regardless of whether allow/deny are good in general, they're not good for the `find` selector. In your example, one would assume that `{ _id: userId }` is a restriction that will always be applied. But Meteor doesn't necessarily run all allow functions.

It's the same thing that confuses all the new people about normal allow functions.

**Comment by stubailo** [comment]
@aldeed I'm also not a fan of allow/deny - I'll take a look at your security package!

**Comment by raix** [comment]
@aldeed I actually never used allow/deny rules twice on a collection, I can see that it's possible - but having an overview of the security makes it easier to reason about (vs. having security declared / scattered in codebase).
Having find in allow/deny rules could be done, the result would look much like the `restrictFind` but getting restrictions from allow/deny rules:
```js
  find({
    $and: [
      userQuery,
      $not: denyRestrictionQuery,
      allowRestrictionQuery
    ]
  });
```
*Declaring multiple allow/deny rules for this is possible - but like `insert/remove/update` might not be easy to reason about*

I lean more against declaring things in a schema pr. field and role giving a nice overview + we could create tooling for generating schema files eventually.

**Comment by stubailo** [comment]
I think I'm recommending Restivus for apps that don't have publications they want to reuse.
