### ISSUE TITLE
add get method in meteor method

### ISSUE THREAD

**Issue by anbuselvan** [stubailo/meteor-rest#19]
How to use meteor method to work with get request? 

I don't want to use meteor publish for get request since I want to provide custom error when there is an issue. I'm creating method like this.

```js
Meteor.method('notes', function() {
  if (this.userId) {
    var notes = Notes.find({userId: this.userId}).fetch();
    return {status: 'success', data: notes};
  } else {
    return {status: 'fail', reason: 'unauthorized access'};
  }
}, {
  url: 'api/v1/notes'
});
```

and from the api-routes I can see the below. 

```js
{
  _id: "/api/v1/notes",
  methods: [
   "options",
   "post"
  ],
  path: "/api/v1/notes"
},
```

How can I remove the post and add get in the methods array?

**Comment by stubailo** [comment]
Currently, there is not a great way to do this - I guess what you're looking for is a way to define an HTTP API endpoint without having a Meteor method or publication that directly matches it?

I think this also merits splitting out some of the internal functionality of this package - for example, the ability to define an HTTP method that deals with `userId` correctly.

**Comment by kahmali** [comment]
I think what @anbuselvan is requesting is just an option in `Meteor.method` to configure the HTTP method of the autogenerated REST endpoint. So something like this:
```javascript
Meteor.method('notes', function() {
  // Do some work here
}, {
  url: 'api/v1/notes',
  httpMethod: 'GET'
});
```

So instead of generating a POST endpoint, this would generate a GET endpoint.

**Comment by anbuselvan** [comment]
thanks @kahmali that works best.. everything already there.. just need another option to override the defaults.

**Comment by anbuselvan** [comment]
I do agree with you @stubailo.. the request still needs to be optionally authenticated..

I think this should still work..
```bash
curl -H "Authorization: Bearer <token>"  http://localhost:3000/api/v1/notes
```

**Comment by stubailo** [comment]
OK! That makes sense. I'll just add an option for `httpMethod` in the next version.

**Comment by anbuselvan** [comment]
awesome! cool thanks @stubailo and @kahmali.

**Comment by stubailo** [comment]
Published this feature in 0.2.3!

**Comment by stubailo** [comment]
Documented here: https://github.com/stubailo/meteor-rest/blob/master/packages/rest/README.md#available-options

**Comment by anbuselvan** [comment]
Verified! thanks @stubailo!!
