### ISSUE TITLE
How to prevent meteor publish not automatically exposed as apis

### ISSUE THREAD

**Issue by anbuselvan** [stubailo/meteor-rest#20]
There should be an option when publishing collections to not expose them as apis, same thing for methods.

from meteor publish
```js
{
  _id: "/notes",
  methods: [
    "options",
    "post"
  ],
  path: "/notes"
},
{
  _id: "/notes/:_id",
  methods: [
    "options",
    "patch",
    "options",
    "delete"
  ],
  path: "/notes/:_id"
},
```

from meteor method
```js
{
  _id: "/api/v1/notes",
  methods: [
    "options",
    "post"
  ],
  path: "/api/v1/notes"
},
```

it's actually creating a duplicate api endpoint that I don't want to expose.

Similarly the methods also should be able to prevented to expose.

from meteor methods
```js
{
  _id: "/methods/addnote",
  methods: [
    "options",
    "post"
  ],
  path: "/methods/addnote"
},
```

from meteor method
```js
{
  _id: "/api/v1/addnote",
  methods: [
    "options",
    "post"
  ],
  path: "/api/v1/addnote"
}
```

it's creating duplicate apis with multiple endpoints.

**Comment by stubailo** [comment]
Can you give me a code sample? I'm not exactly sure what you are doing that is causing the duplicate endpoints.

However, I'm also strongly considering separating this package into two or more:

1. A package to expose a publication, method, or collection
2. A package that automatically does it for all of your methods, publications, and collections (this one)

Is that what you're looking for? Just a way to not do it automatically?

**Comment by anbuselvan** [comment]
sure.. I want the endpoint should be prefixed with 'api/v1' in all the exposed apis. Also I still don't want to touch the existing methods and publications defined for non-api version.

Non-api (!) version already defined and being used from the web client.
```js
Meteor.methods({
  addnote: function(note) {
    if (this.userId) {
      Notes.insert({userId:this.userId, note: data.note});
    }
  }
});
```

api version for mobile devices
```js
Meteor.method('add-note', function(data) {
  if (this.userId) {
    Notes.insert({userId:this.userId, note: data.note});
    return {status: 'success'};
  } else {
    return {status: 'fail', reason: 'unauthorized access'};
  }
}, {
  url: 'api/v1/addnote'
});
```

**Comment by anbuselvan** [comment]
Can it be something simple like when I set the url = null then it'll not be exposed.

```js
Meteor.method('add-note', function(data) {
  if (this.userId) {
    Notes.insert({userId:this.userId, note: data.note});
    return {status: 'success'};
  } else {
    return {status: 'fail', reason: 'unauthorized access'};
  }
}, {
  url: null
});
```

Does it make sense? can it be that simple?

**Comment by stubailo** [comment]
I'm just wondering why you would want to have different endpoints and API for the mobile app vs. the desktop app? Don't they display the same data at the end of the day?

**Comment by anbuselvan** [comment]
but I want to hide or make it private few methods and publications only for those using my websites, currently it exposes everything..

**Comment by stubailo** [comment]
@anbuselvan I think there is a flaw in your reasoning here - if the frontend of your Meteor app can access a method, then anyone can. Someone could use any DDP client, connect to your app, and use it as an API. Doing it over an HTTP endpoint isn't any more or less secure.

**Comment by anbuselvan** [comment]
@stubailo I totally agree with you on this.

I just moved the collections inside the server folder, and I'm not able to access the Notes collection from browser console, which means no body can access to it, but I'm seeing the collection available in the api list from /publications/api-routes.

is that the expected behavior?

**Comment by stubailo** [comment]
There's a difference between what you can type in the browser console, and what data someone connected to your server can actually access.

Read some articles about security in Meteor:
1. http://docs.meteor.com/#/full/allow
2. http://joshowens.me/meteor-security-101/
3. https://www.discovermeteor.com/blog/meteor-and-security/

Basically, the point here is that people can write _their own code_ to interface with your server. Even if your app doesn't declare a client-side collection, someone could create one in the browser console. Or, they could write totally new client-side code to interface with your server. You need to secure your app by using Methods, allow/deny, or some other security package for Meteor; then the API endpoints generated by this package will be secured as well.

**Comment by anbuselvan** [comment]
Cool, thanks for the links @stubailo. I'll look into those to learn more.
