### ISSUE TITLE
Add Continuous Integration for tests

### ISSUE THREAD

**Issue by kahmali** [stubailo/meteor-rest#29]
I'm most familiar with [Travis CI](https://meteorhacks.com/travis-ci-support-for-meteor-packages). Any good CI will have GitHub integration so tests are automatically run when PRs are submitted. I'd be happy to make a PR for this.

**Comment by stubailo** [comment]
Sounds great to me!

**Comment by kahmali** [comment]
@stubailo It looks like collaborators don't have the authorization to enable Travis CI on the repo. You just need to [sign into Travis CI with your GitHub info](https://travis-ci.org/auth) and enable this repo. I _should_ be able to take care of the rest after that.

**Comment by stubailo** [comment]
Just did it!

**Comment by kahmali** [comment]
Awesome!. Thanks @stubailo!

**Comment by kahmali** [comment]
So close on this! https://travis-ci.org/stubailo/meteor-rest/builds/65209397

4/5 test suites are passing, and 20/21 tests passing in the one bad suite (simple:rest). The one failing test is:
```js
testAsyncMulti("Simple REST - mutator methods", [
  function (test, waitFor) {
    HTTP.get("/publications/widgets", waitFor(function (err, res) {
      test.equal(err, null);

      // THIS IS THE FAILING TEST
      // Make sure our special key was saved
      test.isTrue(_.findWhere(res.data.widgets,
        { specialKey: "Over 9000!" }));
    }));
  }
]
```
I'll try to get this fixed by tomorrow. Maybe you have a suggestion @stubailo? It passes locally, and I thought I was able to match the environment on the Travis server, but clearly there's an inconsistency there. 

This should be ready for a PR soon.

**Comment by aldeed** [comment]
@kahmali I fixed the tests and merged. It was actually a sneaky issue due to this phantomjs issue: https://github.com/ariya/phantomjs/issues/11384

Until travis is using phantomjs 2.0, I added checks so that the 2 affected tests will still run locally but will ignore failures when running in a phantom environment.

**Comment by kahmali** [comment]
@aldeed Awesome!! Nice find! Now I can't make stupid mistakes like [this](https://github.com/stubailo/meteor-rest/pull/40#issuecomment-108151136). Thanks!
