### ISSUE TITLE
Setup linter

### ISSUE THREAD

**Issue by kahmali** [stubailo/meteor-rest#34]
- [ ] Convert all strings to single-quotes for consistency

See #27

**Comment by stubailo** [comment]
This would be easier to enforce with a linter (linters are great at detecting quotes :smile: )

**Comment by kahmali** [comment]
Agreed. I updated the title and moved the string quotation issue down as a task.

**Comment by stubailo** [comment]
I think they are usually called "linters" :]

**Comment by stubailo** [comment]
Holy shit, what is this black magic?? Auto-formatting JS code? I didn't know such a thing could work. Awesome!

**Comment by aldeed** [comment]
I know! Actually this is the first time I tried jscs, but it worked pretty much perfectly once I had the correct config.
