### ISSUE TITLE
simple:rest 1.0 release

### ISSUE THREAD

**Issue by stubailo** [stubailo/meteor-rest#45]
I don't think we are quite ready for 1.0 yet - there is a lot to figure out around error handling, configuration, documentation, etc. But we should start tracking what will go in the next release.

- [x] Merge bearer token middleware https://github.com/stubailo/meteor-rest/pull/40
- [x] Merge error handling #39 
- [x] Merge error middleware #43
- [x] Document middleware system
- [ ] Update version numbers for all packages
- [x] Figure out if there are any breaking changes
- [ ] Update documentation in general

**Comment by aldeed** [comment]
@stubailo, this has been on my to-do list for awhile. We have been using commit b525409ad05390039496d34829ef707585cbd3ec in production for a couple months. I will start looking into the remaining tasks above.

**Comment by stubailo** [comment]
Haha, yeah I've really been dragging my feet on this too, and things have gotten pretty busy around the office. Let me know how I can help!

**Comment by aldeed** [comment]
I'll try to work with @kahmali to get the middleware package merged and documented. The rest is fairly trivial.

**Comment by aldeed** [comment]
@stubailo I think all the important issues and PRs are done now. There are breaking changes so it should be the 2.0 release. I will let you look over everything, make sure the change logs and the readmes are complete, and bump/publish.

You might want to sneak in a fix for #54, too, if it is easy.

**Comment by stubailo** [comment]
Wow, awesome! Going to look over this stuff tomorrow and try to ship it,
thanks for tearing through all of the issues!

**Comment by stubailo** [comment]
Is 1.0 enough of a version bump? I think the version solver won't automatically go from 0.2 -> 1.0, so we probably don't need to skip to 2.0.

**Comment by aldeed** [comment]
@stubailo Oh, right. Some packages are at 1.x but simple:rest isn't yet. Here's my thinking by package:

- `json-routes`. Breaking changes and already at 1.0.4 so should be bumped to 2.0
- `rest` Lots of breaking changes. 1.0
- `rest-accounts-password` Just switched to use middleware, but no breaking changes I think so 1.1 maybe.
- `authenticate-user-by-token` New package. 0.0.1 or 1.0
- `rest-bearer-token-parser` New package. 0.0.1 or 1.0
- `rest-json-error-hander` New package. 0.0.1 or 1.0

**Comment by tcastelli** [comment]
+1 for new release :)

**Comment by aldeed** [comment]
@stubailo Anything else you need from me to be able to publish these?

**Comment by stubailo** [comment]
No, just time... sorry about that. I'll try to do it this week.

**Comment by aldeed** [comment]
Ah, time... the one thing of which I have no extra. :)

**Comment by alexpyslar** [comment]
Hi guys, just wanted to know if are there any news related with:
authenticate-user-by-token New package. 0.0.1 or 1.0
rest-bearer-token-parser New package. 0.0.1 or 1.0
rest-json-error-hander New package. 0.0.1 or 1.0
?
Thanks!

**Comment by stubailo** [comment]
OK I finally sat down and made myself do it, I went with the version numbers @aldeed proposed.

simple:rest 1.0 is out!

Thank you so much to everyone for your help.

**Comment by aldeed** [comment]
Awesome!
