### ISSUE TITLE
[json-routes] Accept dictionary of headers in sendResult() and sendError()

### ISSUE THREAD

**Issue by kahmali** [stubailo/meteor-rest#46]
It seems inconsistent to allow all response information to be passed into these methods except for the headers, when there is nothing unique about the headers. For those, a user has to pass the dictionary to [`JsonRoutes.setResponseHeaders()`](https://github.com/stubailo/meteor-rest/blob/devel/packages/json-routes/json-routes.js#L54), which stores the headers in an [object](https://github.com/stubailo/meteor-rest/blob/devel/packages/json-routes/json-routes.js#L49) until they are later added to the response from [within the `sendResult() method](https://github.com/stubailo/meteor-rest/blob/devel/packages/json-routes/json-routes.js#L116), which calls a method [`setHeaders()`](https://github.com/stubailo/meteor-rest/blob/devel/packages/json-routes/json-routes.js#L134) to iterate over the headers dictionary and set each header in the response. 

If that sounds kind of convoluted, it's because it is. I think it would make a lot more sense to just pass the dictionary of headers directly to `sendResult()` and `sendError`. Then the same `setHeaders()` function can be used to set those response headers.

We can still provide a method for endpoints or middleware to contribute to the headers if that's desirable.

**Comment by stubailo** [comment]
That makes sense - ideally at that point `sendResult` will just take keyword args like so:

```js
JsonRoutes.sendResult(res, {
  code: code,
  data: data,
  headers: headers,
  // ...etc
});
```

**Comment by kahmali** [comment]
That looks good @stubailo
