### ISSUE TITLE
Missing commit on devel

### ISSUE THREAD

**Issue by kahmali** [stubailo/meteor-rest#51]
What happened to [this commit](https://github.com/stubailo/meteor-rest/commit/b525409ad05390039496d34829ef707585cbd3ec) on the latest version of [devel](https://github.com/stubailo/meteor-rest/commits/devel)? I have work based off of it in a feature branch. I suppose I'll get to learn something new about git to resolve it, which certainly isn't the worst thing in the world.

**Comment by aldeed** [comment]
I'm not sure, but you can still do a PR from https://github.com/stubailo/meteor-rest/compare/issue/%2338-change-logs
