### ISSUE TITLE
[Feature Request] Don´t publish all methods and collections

### ISSUE THREAD

**Issue by jhuenges** [stubailo/meteor-rest#52]
As @stubailo mentioned [here](https://github.com/stubailo/meteor-rest/issues/20) how about a second package that does not automatically expose all methods and collections?

**Comment by jhuenges** [comment]
*bump*

**Comment by stubailo** [comment]
Yeah, that's a good idea - when I get a chance I'll build it. Why do you want this feature, though? If it's for security you should be advised that your methods and publications can be called easily over DDP as well.

**Comment by jhuenges** [comment]
Yeah, I am aware of the possibility to connect via DDP. Its just something I thought about.
