### ISSUE TITLE
Customise user not found text in simple:rest-accounts-password

### ISSUE THREAD

**Issue by scsirdx** [stubailo/meteor-rest#55]
Now simple:rest-accounts-password respond with "not-found", "User with that username or email address not found." when user not found, and 403, "Incorrect password" when password didn't match.
This is not good from a security standpoint. I made a quick hack to local copy of simple:rest-accounts-password, so now it respond "Login failed".
But maybe it will be better to make message customisable?

**Comment by aldeed** [comment]
I think these match the DDP errors, so really this is something that should be configurable in the accounts-password package so that it's the same for DDP and HTTP.

Still, you'll probably be able to override this in the next version of simple:rest using custom error handling middleware.
