### ISSUE TITLE
Do something about apps with `autopublish`

### ISSUE THREAD

**Issue by stubailo** [stubailo/meteor-rest#6]
Since they don't have publications, there is no way to get the data.

**Comment by stubailo** [comment]
Maybe define a default publication with all data for a certain collection?

**Comment by aldeed** [comment]
If you need REST but you still have autopublish, there's probably something wrong there. :)

Maybe a single GET handler that runs if the path doesn't match anything else, checks to see whether the first url piece matches the name of any collection. Define that handler only if autopublish package is used. Some kind of basic sort/limit/skip with that.
