### ISSUE TITLE
Specify url for publishComposite publications

### ISSUE THREAD

**Issue by woniesong92** [stubailo/meteor-rest#64]
Is there a way to specify urls (add param values) for publishComposite publications?

**Comment by woniesong92** [comment]
Also, is there a way to specify a url of a publication like this?

`url: "/api/posts?limit=:0&skip:1"`

based on my experience, only the following works:

`url: "/api/posts/:0/:1"`

**Comment by stubailo** [comment]
You can use the `getArgsFromRequest` option (documented in the simple:rest README) to create a function that takes in a Node request object, and generates arguments. So you could access the query parameters from there. In the default URL parser there is no way to get query params.

**Comment by Diwei-Chen** [comment]
Can someone confirm `getArgsFromRequest ` works with publishComposite? 

It doesn't seem like working for me.
