### ISSUE TITLE
Content-Type required when using CURL?

### ISSUE THREAD

**Issue by timbrandin** [stubailo/meteor-rest#65]
Hi, just wanted to note that the content type is required also when calling through curl, I think this should be the default content type instead of forcing us to pass it along with the curl request.

**Comment by stubailo** [comment]
The big issue is that form encoding doesn't have any way to specify non-string arguments, so I chose json encoding as the default. You can use options or JsonRoutes middlewares to make it accept form encoding.

**Comment by timbrandin** [comment]
oh alright, thx
