### ISSUE TITLE
Get the automatically published user data

### ISSUE THREAD

**Issue by stubailo** [stubailo/meteor-rest#7]
The data passed to the client that goes in `Meteor.user()` is currently not retrievable. Need to make an endpoint for this.

**Comment by raix** [comment]
Could be related to #15 if solved eg. by setting up:
```js
Meteor.users.allow({
  find: function(userId) {
    // Allow user to find data about it self
    return { _id: userId };
  }
});
```

Opens op, allowing the user to do:
```js
  HTTP.get('api/users/xu4ijs2h2hk2', /* ... */);
  // or
  HTTP.get('api/users?_id=xu4ijs2h2hk2');
```

Given a default publish for collections are rigged:
```js
  Meteor.publish('users', function(userId) {
    Accounts.runAsUser(this.userId, function() {
      if (userId === ''+userId) {
        // This a user id, find is restricted running as a user
        return Meteor.users.find({ _id: userId });
      } else {
        // We are handed in the named arguments
        var query = namedArgumentsToAndQuery(userId);
        // Return the restricted find for the user
        return Meteor.users.find(query);
      }
    });
  });
```

**Comment by aldeed** [comment]
Somewhere there's an issue about how the user publication should be named because there's no way to wait on a null publication. Maybe just fix that instead. :)

Would that actually fix it, or would accounts package need to depend on simple:rest?
