### ISSUE TITLE
Allow configuration of request entity size limit (or at least increase it in the interim)

### ISSUE THREAD

**Issue by kahmali** [stubailo/meteor-rest#75]
It appears that some of the connect middleware defined [here](https://github.com/stubailo/meteor-rest/blob/devel/packages/json-routes/json-routes.js#L9) is imposing a size limit on the request body that it will parse. If they have the same API as the Connect bodyParser we replaced there (and according to [this SO answer](http://stackoverflow.com/a/20028862/2280663), they do), the urlencoded and json parsers should accept an argument in the form `connect.urlencoded({limit: '10mb'})`. I would update this myself, but I'm swamped right now and don't have time to add the testing and update the docs and such. Sorry about that. A Restivus user recently [reported an issue](https://github.com/kahmali/meteor-restivus/issues/78#issuecomment-160141010) with it. I'll point them here for further discussion.

**Comment by snowping** [comment]
I got the issue "Error: request entity too large" and I assume I need to increase the size limit of the request body. Is there any workaround yet or do I need to fork and tweak the sources?

Thanks

**Comment by ramzauchenna** [comment]
@kahmali any luck fixing this i also have the exact same issue and i use restivus awesome package

**Comment by ramzauchenna** [comment]
me too. This issue is a serious problem restivus users

**Comment by snowping** [comment]
In case anyone is interested I forked the package json-routes and hardcoded the limit to 50mb (quick and dirty fix). You can find the git project here: https://github.com/snowping/meteor.json-routes. If it solves your problem right away you can also add it using `meteor add snowping:json-routes`.

**Comment by stubailo** [comment]
@snowping if you submit a PR here I can update the real package.

**Comment by snowping** [comment]
@stubailo ok I made a pull request, it only increases the request size to 50mb (hardcoded).

**Comment by stubailo** [comment]
Done and published as json-routes 2.0.1!

Thanks for the PR!
