### ISSUE TITLE
some packages are not available on Atmosphere

### ISSUE THREAD

**Issue by xavierpriour** [stubailo/meteor-rest#78]
Hi, the following are not available on Atmosphere, while the other packages are:

- simple:authenticate-user-by-token
- simple:rest-json-error-handler
- simple:rest-bearer-token-parser

I'd love to use simple:authenticate-user-by-token with simple:json-routes, is there any reason why they're not published?

**Comment by tcastelli** [comment]
This is related to #45 ,  just time is needed to get everything checked, merged and published if I'm not wrong

**Comment by stubailo** [comment]
Just published everything!
