### ISSUE TITLE
JsonRoutes options route doesn't work

### ISSUE THREAD

**Issue by navinSing** [stubailo/meteor-rest#85]
JsonRoutes.add("options", "/con", function (req, res, next) {
  JsonRoutes.sendResult(res, {
        code:200,
        data:{}
        header:{
            'Content-Type': 'application/json; charset=utf-8'
        }
    });
}

The above code is not working for options method

**Comment by stubailo** [comment]
Can you give me more detail about what happens and what you would expect to happen in this case? Ideally, there would be a reproduction I can run. I know that OPTIONS works for CORS method calls, so it would be surprising if it didn't work in this case.

**Comment by navinSing** [comment]
There was just a message... Internal server error... That's it .. No
stacktrace.
Tried all sorts of things with data, without data.. But same error.

Can you give an working example. Thanks

**Comment by stubailo** [comment]
It would be easier if you could give me a non-working example to debug - do you have one around?

**Comment by navinSing** [comment]
Just hello world with.. Simple:json-route and the above mentioned code.
That's what it had.

**Comment by navinSing** [comment]
JsonRoutes.sendResult(res, {
        code:200,
        header:{
// THIS DOESN'T SEAMS TO WORK .. POTENTIAL BUG!
// NOTE: DEFAULT ALL HEADERS WORK..
// WITH A NEW METEOR , AND json-routes v2.0.0
}
});
can check via : 
 curl  -i -X OPTIONS http://localhost:3000/cot

**Comment by navinSing** [comment]
Hi, 

did you got chance to look into .. 

Thanks

**Comment by navinSing** [comment]
using default headers to do the job :)

**Comment by stubailo** [comment]
Sorry, I've been so busy with other stuff :/

**Comment by crapthings** [comment]
@navinSing 

how to solve this Content-Type': 'application/json; charset=utf-8

i have to make the route readable
