### ISSUE TITLE
Where does `req.userId` comes from?

### ISSUE THREAD

**Issue by dotansimha** [stubailo/meteor-rest#86]
Hi @stubailo ,
Tried to use the package with the accounts-password package. 
The login works great, and I send each request with the correct headers (`Authorization: Bearer...`). 
In my collection I defined `allow` callback and tried to use `this.userId` but it is always `null`.
Took a look at the package source code, and found the the source of the `userId` params is from the request callback, which initially comes from `connect`. 
The only thing I'm missing it where `req.userId` comes from in this line https://github.com/stubailo/meteor-rest/blob/devel/packages/rest/rest.js#L196

Thanks !

**Comment by stubailo** [comment]
I think we might have messed up a bit on the docs. Basically, you need to add two middlewares, one to parse the token and another to get the user:

https://github.com/stubailo/meteor-rest/tree/devel/packages/authenticate-user-by-token#usage

Let me know if that works for you.

**Comment by dotansimha** [comment]
Thanks @stubailo !! I will try it and re-open if it does not work.
