### ISSUE TITLE
SimpleRest is not defined

### ISSUE THREAD

**Issue by jarinwhite** [stubailo/meteor-rest#90]
I am trying to create a very simple local package that will configure some SimpleRest options. The package.js file includes

`api.use('simple:rest')`

and the actual package contents consists only of

`SimpleRest.configure({
    objectIdCollections: ['items']
});`

However, Meteor throws an error "SimpleRest is not defined". I was under the impression that the simple:rest package exported the SimpleRest symbol, but looking through the package source in the build folder, that does not appear to be the case. Surely i am doing something obviously wrong. Can anyone offer some insight?

Much appreciated,
Jarin

**Comment by stubailo** [comment]
@jarinwhite did you specify which version of `simple:rest` you want to use in your package? Meteor doesn't automatically select the latest version.

**Comment by valorloff** [comment]
import SimpleRest from 'meteor/simple:rest@1.1.1';  // Error: Can't find npm module
import {SimpleRest} from 'meteor/simple:rest'; // TypeError: Cannot read property 'SimpleRest' of undefined
import SimpleRest from 'meteor/simple:rest'; // TypeError: Cannot call method 'setMethodOptions' of undefined

how to??

**Comment by stubailo** [comment]
```
import {SimpleRest} from 'meteor/simple:rest';
```

This should be the correct one. Can you post the stack trace you got here?

**Comment by ixgaming** [comment]
Hi,

do you have solved this problem ? I encounter the same problem with my project.

**Comment by ixgaming** [comment]
Hello i am having problem to configure simplest : 
structure is as follow : 
client -> all client related files
import -> files accessed by both client and or server
server -> all server related files

in server/main.js i have the following code:

```

import { Meteor } from 'meteor/meteor';
import '../imports/api/tasks.js';

Meteor.startup(() => {
  // code to run on server at startup
    SimpleRest.configure({
        collections: []
    });

    // Enable cross origin requests for all endpoints
    JsonRoutes.setResponseHeaders({
        "Cache-Control": "no-store",
        "Pragma": "no-cache",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, PUT, POST, DELETE, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Requested-With"
    });

});

```

in my imports/api/tasks.js file i have the following : 

```

/**
 * Created by julienlange on 19/06/2016.
 */
import { Meteor } from 'meteor/meteor';
import { Mongo } from 'meteor/mongo';
import { check } from 'meteor/check';

export const Tasks = new Mongo.Collection('tasks');

if (Meteor.isServer) {
    // Only publish tasks that are public or belong to the current user
    Meteor.publish('tasks', function tasksPublication() {
        "use strict";
        return Tasks.find({
            $or: [
                { private: { $ne: true } },
                { owner: this.userId },
            ],
        });
    });
}

Meteor.methods( {
    'tasks.insert'(text) {
        "use strict";
        check(text, String);

        //check if the user is logged in
        if (! this.userId) {
            throw new Meteor.Error('not-authorized');
        }

        Tasks.insert({
            text,
            createdAt: new Date(),
            owner: this.userId,
            username: Meteor.users.findOne(this.userId).username,
        });
    },

    'tasks.remove'(taskId) {
        "use strict";
        check(taskId, String);

        const task = Tasks.findOne(taskId);
        if (task.private && task.owner !== this.userId) {
            // If the task is private, make sure only the owner can delete it
            throw new Meteor.Error('not-authorized');
        }

        Tasks.remove(taskId);
    },
    'tasks.setChecked'(taskId, setChecked) {
        "use strict";
        check(taskId, String);
        check(setChecked, Boolean);
        const task = Tasks.findOne(taskId);

        if (task.private && task.owner !== this.userId) {
            // If the task is private, make sure only the owner can check it off
            throw new Meteor.Error('not-authorized');
        }

        Tasks.update(taskId, { $set: { checked: setChecked}});
    },
    'tasks.setPrivate'(taskId, setToPrivate) {
        check(taskId, String);
        check(setToPrivate, Boolean);

        const task = Tasks.findOne(taskId);

        // Make sure only the task owner can make a task private
        if (task.owner !== this.userId) {
            throw new Meteor.Error('not-authorized');
        }

        Tasks.update(taskId, { $set: { private: setToPrivate } });
    },
})

```

What i want is not exposing tasks publications and methods.

When i use postman : 
GET http://localhost:3000/publications/api-routes

I have the following results : 

```
{
  "api-routes": [
    {
      "_id": "/publications/api-routes",
      "methods": [
        "get"
      ],
      "path": "/publications/api-routes"
    },
    {
      "_id": "/publications/meteor_autoupdate_clientVersions",
      "methods": [
        "get"
      ],
      "path": "/publications/meteor_autoupdate_clientVersions"
    },
    {
      "_id": "/tasks",
      "methods": [
        "options",
        "post"
      ],
      "path": "/tasks"
    },
    {
      "_id": "/tasks/:_id",
      "methods": [
        "options",
        "patch",
        "options",
        "delete"
      ],
      "path": "/tasks/:_id"
    },
    {
      "_id": "/publications/tasks",
      "methods": [
        "get"
      ],
      "path": "/publications/tasks"
    },
    {
      "_id": "/methods/tasks.insert",
      "methods": [
        "options",
        "post"
      ],
      "path": "/methods/tasks.insert"
    },
    {
      "_id": "/methods/tasks.remove",
      "methods": [
        "options",
        "post"
      ],
      "path": "/methods/tasks.remove"
    },
    {
      "_id": "/methods/tasks.setChecked",
      "methods": [
        "options",
        "post"
      ],
      "path": "/methods/tasks.setChecked"
    },
    {
      "_id": "/methods/tasks.setPrivate",
      "methods": [
        "options",
        "post"
      ],
      "path": "/methods/tasks.setPrivate"
    },
    {
      "_id": "/meteor_accounts_loginServiceConfiguration",
      "methods": [
        "options",
        "post"
      ],
      "path": "/meteor_accounts_loginServiceConfiguration"
    },
    {
      "_id": "/meteor_accounts_loginServiceConfiguration/:_id",
      "methods": [
        "options",
        "patch",
        "options",
        "delete"
      ],
      "path": "/meteor_accounts_loginServiceConfiguration/:_id"
    }
  ]
}

```

what is wrong ?
I should not have any api-routes because i configure SimpleRest with 
    SimpleRest.configure({
        collections: []
    });

thanks for your help

**Comment by stubailo** [comment]
> What i want is not exposing tasks publications and methods.

The whole point of this package is exposing your publications and methods. The collections option just removes the default `insert` `update` `remove` methods generated by Meteor. Note that your methods are _already_ exposed over DDP, so there is no additional cost to making them callable over HTTP.

By the way, I don't think it's relevant to this issue, please open a new one.

**Comment by AKGanesh** [comment]
Tried import {SimpleRest} from 'meteor/simple:rest';
giving me the error : cannot find the module meteor/simple:rest';
Using this in a file (custom.ts ex)
Meteor 1.3.3 
versions file has
simple:authenticate-user-by-token@1.0.1
simple:json-routes@2.1.0
simple:rest@1.1.1
simple:rest-accounts-password@1.1.2
simple:rest-bearer-token-parser@1.0.1
simple:rest-json-error-handler@1.0.1

packages file has
simple:rest
simple:json-routes
simple:rest-accounts-password

Thanks for your help !!

**Comment by ManuelAlanis** [comment]
@stubailo I need remove the options, insert update remove for the collections?

These options? 👇

>> Collection.allow({
  'insert': function () {
    return true;
  },
  'update': function () {
    return true;
  },
  'remove': function () {
    return true;
  }
});
