### ISSUE TITLE
JsonRoutes Middleware order for auth token

### ISSUE THREAD

**Issue by atablash** [stubailo/meteor-rest#91]
JsonRoutes.Middleware.parseBearerToken is called after JsonRoutes.Middleware.authenticateMeteorUserByToken.

Does this depend on package loading order?

@kahmali commit https://github.com/stubailo/meteor-rest/commit/82250cb8109c86b680618ff8aeb390158302df2d

**Comment by stubailo** [comment]
I think this actually resulted from the way we ran tests, where we were often including middlewares from other tests. We should make sure to avoid this in the future and run the tests for the different packages individually.

**Comment by stubailo** [comment]
Published this fix as `rest-accounts-password` version `1.1.1`!

**Comment by atablash** [comment]
Cool, thanks!
