### ISSUE TITLE
Token authentication returning always null

### ISSUE THREAD

**Issue by jykae** [stubailo/meteor-rest#95]
Trying token authentication, I suspect that you have unnecessary comma on the line https://github.com/stubailo/meteor-rest/blob/master/packages/authenticate-user-by-token/auth.js#L38
for the database request.

**Comment by jykae** [comment]
I tried the same query in meteor shell without comma successfully.

Should I add this package instead https://github.com/stubailo/meteor-rest/tree/devel/packages/rest-accounts-password ?

Looks like it includes Token authorization despite the package name and conforms better with OAuth standard way.

**Comment by stubailo** [comment]
I don't think the comma actually makes a difference.

And accounts password only lets you _get_ a token, it doesn't actually authorize the HTTP request.

**Comment by stubailo** [comment]
Also, neither of them support basic HTTP auth, or OAuth. So I'm pretty confused about what you are trying to do.

**Comment by jykae** [comment]
That explains why I did not get it to authorize, but I got the token :) Sorry for confusion, I am learning here how your code works. Do you have yet any working authentication method for simple:rest ?

**Comment by jykae** [comment]
We might consider using Restivus as you suggested in the other issue, if authentication is pretty much work in progress. Though the documentation autogeneration would be useful for both projects, I think. Please feel free to close this.

**Comment by stubailo** [comment]
@jykae authentication works great if you get a token from `rest-accounts-password` (which accepts a username and password in the request body) and then parse it using the `rest-bearer-token-parser` and `authenticate-user-by-token` middlewares.

Everything works well, but I see now that the documentation is in a bit of disarray after some refactoring we did recently. Sorry about that.

**Comment by jykae** [comment]
Ok, thanks for info. I did not have rest-accounts-password package in use, and not understood how it should work at first. Closing.
