### ISSUE TITLE
API Token

### ISSUE THREAD

**Issue by rwatts3** [stubailo/meteor-rest#97]
Thank you for building this package.  

Is t possible to use API tokens or do you have an example where a user could request a token and have that token validated as you would with GitHub  or trello ?

**Comment by stubailo** [comment]
You would do this in a middleware. The only example in this package is for getting a token with username/password, and then parsing that:

Here's a route that takes a username/password and returns a token, modeled after how Meteor password login works: https://github.com/stubailo/meteor-rest/blob/ac98582b3002e231a423e3771b2f73fcd1574acf/packages/rest-accounts-password/rest-login.js#L12-L64

Here's a middleware that gets a token out of the request: https://github.com/stubailo/meteor-rest/blob/ac98582b3002e231a423e3771b2f73fcd1574acf/packages/rest-bearer-token-parser/bearer_token_parser.js

Here's a middleware that reads that token and gets a user ID that is then added on to the request object: https://github.com/stubailo/meteor-rest/blob/ac98582b3002e231a423e3771b2f73fcd1574acf/packages/authenticate-user-by-token/auth.js

You should be able to convert those packages to any method of getting a token and associating it with a user or other permissions info.

**Comment by romans127** [comment]
Thank you these are very good points of reference again nice work on this
package.

**Comment by stubailo** [comment]
No problem, hope it works for you!
